#!/usr/bin/env python3
"""Build the English overlay for the ending staff roll as an ASS subtitle file.

The PS2 ending movie (the fifth stream in MOVIE.FPB, 7 min 17 s, 640x448)
has the credits baked into the video: white Japanese text scrolling up the
left side at about 48 pixels per second over the illustrations.  This script
turns `ending_credits.tsv` (one row per credit line, with the moment its top
edge enters the screen, its scroll speed, its height and the x extents of
its text) into an overlay that

  * paints a black box over every Japanese line for exactly as long as it is
    on screen, moving with the scroll, and
  * draws the English translation on top at the same position, and
  * shows a Green Gel card while the Namco logo is on screen at the end.

Burn it into the movie with ffmpeg (libass) before remuxing the PSS:

    python3 ps2/movies/credits_ass.py            # writes ending_credits.ass
    ffmpeg -i ending.pss -vf "ass=ps2/movies/ending_credits.ass" ...

Rows whose English is KEEP are already Latin text or a logo and are left
untouched.  Two-column rows are "left / right" and get one box and one text
per column.  A trailing "?" marks a name reading that could not be verified
and is not printed.
"""
import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
TSV = os.path.join(HERE, 'ending_credits.tsv')
OUT = os.path.join(HERE, 'ending_credits.ass')

W, H = 640, 448
FONT = 'Ubuntu'          # rounded sans close to the original; libass falls back if absent
PAD_X, PAD_Y = 4, 5      # black box margin around the Japanese text
TEXT_DY = -4             # top of the English glyph box relative to the Japanese line top
LEAD = 0.2               # seconds of event before the line enters / after it leaves
TIME_SHIFT = 0.46        # the 1 fps sampling that built the table lags the true timestamps by 22 px (measured)

HEADER = f"""[Script Info]
; Tales of Destiny 2 (PS2) ending staff roll, English overlay
; Generated by ps2/movies/credits_ass.py from ending_credits.tsv
ScriptType: v4.00+
PlayResX: {W}
PlayResY: {H}
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Credit,{FONT},22,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1.2,0,7,0,0,0,1
Style: Box,{FONT},22,&H00000000,&H00000000,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,7,0,0,0,1
Style: Card,{FONT},24,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,1,0,1,1.5,0,2,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def ts(sec):
    sec = max(0.0, sec)
    h = int(sec // 3600)
    m = int(sec % 3600 // 60)
    s = sec % 60
    return f'{h}:{m:02d}:{s:05.2f}'


def events():
    out = []
    for r in csv.DictReader(open(TSV, encoding='utf-8'), delimiter='\t'):
        en = r['english']
        if en == 'KEEP':
            continue
        t0, v, h = float(r['t0']) + TIME_SHIFT, float(r['speed']), int(r['height'])
        segs = [tuple(int(x) for x in s.split('-')) for s in r['segments'].split(';')]
        texts = [t.strip().rstrip('?').strip() for t in en.split(' / ')]
        if len(texts) != len(segs):
            texts = [' '.join(texts)]
            segs = [(segs[0][0], segs[-1][1])]
        start = t0 - LEAD
        end = t0 + (H + h + 2 * PAD_Y) / v + LEAD
        y_start = H - v * (start - t0)        # line top at event start (below the screen)
        y_end = H - v * (end - t0)            # line top at event end (above the screen)
        two = len(segs) == 2
        for (xa, xb), text in zip(segs, texts):
            bw, bh = xb - xa + 2 * PAD_X, h + 2 * PAD_Y
            box = (f'{{\\an7\\move({xa - PAD_X},{y_start - PAD_Y:.1f},{xa - PAD_X},{y_end - PAD_Y:.1f})'
                   f'\\p1\\bord0\\shad0\\1c&H000000&}}m 0 0 l {bw} 0 l {bw} {bh} l 0 {bh}{{\\p0}}')
            out.append((0, start, end, 'Box', box))
            size = h + 3
            scale = '\\fscx90' if two else ''
            txt = (f'{{\\an7\\move({xa},{y_start + TEXT_DY:.1f},{xa},{y_end + TEXT_DY:.1f})'
                   f'\\fs{size}{scale}}}{text}')
            out.append((1, start, end, 'Credit', txt))
    # Green Gel card while the Namco logo is on screen (black gap + logo).
    out.append((1, 426.2, 436.6, 'Card',
                '{\\an2\\pos(320,420)\\fad(600,600)}English translation patch\\NGreen Gel'))
    return out


def main():
    lines = [HEADER]
    for layer, start, end, style, text in events():
        lines.append(f'Dialogue: {layer},{ts(start)},{ts(end)},{style},,0,0,0,,{text}\n')
    open(OUT, 'w', encoding='utf-8').write(''.join(lines))
    print(f'wrote {OUT}: {len(lines) - 1} events')


if __name__ == '__main__':
    main()
