"""Bake the glyph bitmaps that title_credit.py draws with (developer tool).

    python3 ps2/menu/bake_title_glyphs.py [path/to/LiberationSans-Bold.ttf]

Writes ps2/menu/title_glyphs.py. Needs Pillow and the Liberation Sans Bold
font (SIL Open Font License 1.1, https://github.com/liberationfonts). The
build tools themselves only import the generated module, so people applying
the patch need neither Pillow nor the font.

Two styles are baked from the same face at 13 px (cap height 9 px, matching
the copyright line already on the title screen):
  ps2  normal width, for the 384x32 PS2 strip
  psp  condensed to 80 percent, for the 128x32 PSP strip
Every glyph is rasterised alone at its final size (hinted, so the stems
stay crisp) and only the PSP style is then squeezed horizontally; advance
widths are fractional and the layout code accumulates them.
"""
import os, sys, base64
from PIL import Image, ImageFont, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "title_glyphs.py")
SIZE = 13
BAND = 16            # rows of the strip a line occupies
CAP_BOTTOM = 13      # row holding the bottom of capital letters
STYLES = {"ps2": 1.0, "psp": 0.80}
CHARS = [chr(c) for c in range(0x20, 0x7F)]

def find_font(argv):
    cands = argv[1:] + [
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf",
        "C:/Windows/Fonts/LiberationSans-Bold.ttf",
    ]
    for c in cands:
        if os.path.isfile(c):
            return c
    raise SystemExit("LiberationSans-Bold.ttf not found; pass its path")

def bake(font_path):
    font = ImageFont.truetype(font_path, SIZE)
    hb = font.getbbox("H")                      # (x0, y0, x1, y1) from the pen
    styles = {}
    for name, xscale in STYLES.items():
        glyphs = {}
        for ch in CHARS:
            adv = font.getlength(ch) * xscale
            bb = font.getbbox(ch)
            if ch == " " or bb is None or bb[2] <= bb[0]:
                glyphs[ch] = (round(adv, 3), 0, 0, 0, 0, "")
                continue
            # canvas as tall as the band, glyph drawn with its capital bottom
            # on row CAP_BOTTOM, x origin at 0 (the pen position)
            W = int(bb[2] + 4)
            im = Image.new("L", (W, BAND), 0)
            ty = CAP_BOTTOM + 1 - hb[3]
            ImageDraw.Draw(im).text((0, ty), ch, font=font, fill=255)
            small = im if xscale == 1.0 else im.resize(
                (max(1, round(W * xscale)), BAND), Image.LANCZOS)
            box = small.getbbox()
            if box is None:
                glyphs[ch] = (round(adv, 3), 0, 0, 0, 0, "")
                continue
            crop = small.crop(box)
            glyphs[ch] = (round(adv, 3), box[0], box[1], crop.width, crop.height,
                          base64.b64encode(crop.tobytes()).decode())
        styles[name] = glyphs
    return styles

def main():
    font_path = find_font(sys.argv)
    styles = bake(font_path)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write('"""Glyph bitmaps for title_credit.py. GENERATED by bake_title_glyphs.py,\n'
                'do not edit by hand.\n\n'
                'Rasterised from Liberation Sans Bold (Copyright 2012 Red Hat, Inc.,\n'
                'SIL Open Font License 1.1). Each entry: char -> (advance, x, y, w, h,\n'
                'base64 of w*h 8-bit coverage), positioned for a %d-row band with the\n'
                'capital baseline on row %d.\n"""\n' % (BAND, CAP_BOTTOM))
        f.write("BAND = %d\nCAP_BOTTOM = %d\n" % (BAND, CAP_BOTTOM))
        f.write("STYLES = {\n")
        for name, glyphs in styles.items():
            f.write("  %r: {\n" % name)
            for ch, rec in glyphs.items():
                f.write("    %r: %r,\n" % (ch, rec))
            f.write("  },\n")
        f.write("}\n")
    print("wrote", OUT, "from", font_path)

if __name__ == "__main__":
    main()
